language: ruby
script: bundle exec rake
rvm:
  - 2.2
  - 2.3
  - 2.4
  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head

gemfile:
  - gemfiles/rack_cache_1.6.gemfile
  - gemfiles/rack_cache_1.7.gemfile
