language: ruby
before_install: gem install bundler
script: 'bundle exec rake'
rvm:
  - 2.2.2
  - 2.3.1
  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
# Put this in your .travis.yml
gemfile:
  - gemfiles/rack_cache_1.6.gemfile
  - gemfiles/rack_cache_1.7.gemfile
