name: Tests
on: [push]
jobs:
  test:
    name: Run Automated Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.4
          - 2.5
          - 2.6
          - 2.7
        gemfile:
          - rack_cache_1.6
          - rack_cache_1.7
          - rack_cache_1.8
          - rack_cache_1.9
          - rack_cache_1.10
          - rack_cache_1.11
          - rack_cache_1.12
          - rack_cache_latest
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1.1.1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: bundle install
      - run: bundle exec rake
